name: Brighton Ruby Conference 2020
description: A one day conference in Brighton for Rubyists

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
include: ['_redirects']
permalink: /:year/:title/
future: true
url: 'https://brightonruby.com'

sass:
  style: :compressed

collections:
  archives:
    output: true
    permalink: /:path/
    layout: archive
  misc:
    output: true
    permalink: /misc/:path/

gems:
  - jekyll-redirect-from
